version: '2'
services:
  web:
    image: gitlab.effectiveinc.com:4567/pwc/track-proto:develop
    command: ./node_modules/.bin/gulp serve
    environment:
      - NODE_ENV=development
    labels:
      rap.host: "pwc.track-proto.dev.effective.net"
      rap.port: "3000"
